name: gnn-env

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.10

  # PyTorch CPU
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - cpuonly

  # Core scientific stack
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - networkx
  - pyyaml
  - tqdm
  - joblib
  - seaborn

  - pip

  - pip:
      - torch-geometric==2.7.0
      - aiohttp
      - fsspec
      - psutil
      - xxhash
